// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmo2AK11usBvQuX5FZjxZEd0lpU5qNfiU',
    appId: '1:981859855978:web:0bef69809b18e83fc62413',
    messagingSenderId: '981859855978',
    projectId: 'easacctask-c51d9',
    authDomain: 'easacctask-c51d9.firebaseapp.com',
    storageBucket: 'easacctask-c51d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHWVANM39L33fnL8q8WIPUiW5hFlIVVA4',
    appId: '1:981859855978:android:17c411c5acb746dcc62413',
    messagingSenderId: '981859855978',
    projectId: 'easacctask-c51d9',
    storageBucket: 'easacctask-c51d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4y7xwjmAYeJFfBS4cXKPdQeTAMbE6Asc',
    appId: '1:981859855978:ios:7bfd2f0860e83783c62413',
    messagingSenderId: '981859855978',
    projectId: 'easacctask-c51d9',
    storageBucket: 'easacctask-c51d9.firebasestorage.app',
    iosBundleId: 'com.easacc.easacctask',
  );
}
